# Generated by Django 5.2.4 on 2025-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideahistory',
            name='marketing_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideahistory',
            name='roadmap_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
