# Generated by Django 5.2.4 on 2025-07-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_ideahistory_marketing_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideahistory',
            name='marketing_output',
        ),
        migrations.RemoveField(
            model_name='ideahistory',
            name='roadmap_output',
        ),
    ]
